version: '3.6'


services:
  app:
    build: .
    container_name: Backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres_db:5432/postgres
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: 12345

  postgres_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

volumes:
  postgres_data:
    driver: local